#!/usr/bin/env bash
# Configure future shells for pto-auth-proxy. A token (or a legacy password)
# is accepted on stdin so it never appears in argv or the process environment.
set -Eeuo pipefail

PROXY_USER=${1:-$(id -un)}
HTTP_HOST=${PTO_AUTH_PROXY_LISTEN_HOST:-127.0.0.1}
HTTP_PORT=${PTO_AUTH_PROXY_HTTP_PORT:-20809}
SOCKS_PORT=${PTO_AUTH_PROXY_SOCKS_PORT:-20808}
CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}/pto-auth-proxy
SECRET_FILE=$CONFIG_HOME/secret-uri
ENV_FILE=$CONFIG_HOME/env.sh
BEGIN_MARKER='# >>> pto-auth-proxy managed environment >>>'
END_MARKER='# <<< pto-auth-proxy managed environment <<<'
LEGACY_BEGIN_MARKER='# ---- 686 authenticated proxy ----'
LEGACY_END_MARKER='# ---------------------------------'

[[ "$PROXY_USER" =~ ^[a-zA-Z0-9_.-]+$ ]] || {
    echo "Invalid proxy username: $PROXY_USER" >&2
    exit 2
}
[[ "$HTTP_PORT" =~ ^[0-9]+$ ]] && ((10#$HTTP_PORT >= 1 && 10#$HTTP_PORT <= 65535)) || {
    echo "Invalid HTTP proxy port: $HTTP_PORT" >&2
    exit 2
}
[[ "$SOCKS_PORT" =~ ^[0-9]+$ ]] && ((10#$SOCKS_PORT >= 1 && 10#$SOCKS_PORT <= 65535)) || {
    echo "Invalid SOCKS5 proxy port: $SOCKS_PORT" >&2
    exit 2
}

case "$HTTP_HOST" in
    *:*) HTTP_URL_HOST="[$HTTP_HOST]" ;;
    *) HTTP_URL_HOST=$HTTP_HOST ;;
esac

if [[ -n ${PTO_AUTH_PROXY_SHELL_RC:-} ]]; then
    SHELL_RC=$PTO_AUTH_PROXY_SHELL_RC
else
    case "${SHELL:-/bin/bash}" in
        */zsh) SHELL_RC=$HOME/.zshrc ;;
        *) SHELL_RC=$HOME/.bashrc ;;
    esac
fi

# Preserve dotfile-manager symlinks by editing their target, not replacing the
# link itself. Refuse malformed managed blocks before writing any credential.
SHELL_RC_DISPLAY=$SHELL_RC
if [[ -L "$SHELL_RC" ]]; then
    SHELL_RC=$(readlink -f -- "$SHELL_RC") || {
        echo "Shell startup file is a dangling symlink: $SHELL_RC_DISPLAY" >&2
        exit 1
    }
fi
if [[ ! -e "$SHELL_RC" ]]; then
    install -m 0644 /dev/null "$SHELL_RC"
fi
[[ -f "$SHELL_RC" && -w "$SHELL_RC" ]] || {
    echo "Shell startup file is not writable: $SHELL_RC_DISPLAY" >&2
    exit 1
}

begin_count=$(grep -Fxc "$BEGIN_MARKER" "$SHELL_RC" || true)
end_count=$(grep -Fxc "$END_MARKER" "$SHELL_RC" || true)
legacy_begin_count=$(grep -Fxc "$LEGACY_BEGIN_MARKER" "$SHELL_RC" || true)
legacy_end_count=$(grep -Fxc "$LEGACY_END_MARKER" "$SHELL_RC" || true)
if ((begin_count != end_count || begin_count > 1 ||
     legacy_begin_count != legacy_end_count || legacy_begin_count > 1)); then
    echo "Refusing to edit malformed proxy block in $SHELL_RC_DISPLAY" >&2
    exit 1
fi

PROXY_CREDENTIAL=
IFS= read -r PROXY_CREDENTIAL || true
[[ -n "$PROXY_CREDENTIAL" ]] || {
    echo "Proxy credential was not provided on stdin" >&2
    exit 2
}

install -d -m 0700 "$CONFIG_HOME"
secret_tmp=$(mktemp "$CONFIG_HOME/.secret-uri.XXXXXX")
env_tmp=$(mktemp "$CONFIG_HOME/.env.sh.XXXXXX")
rc_tmp=
cleanup() {
    rm -f -- "$secret_tmp" "$env_tmp"
    [[ -z "$rc_tmp" ]] || rm -f -- "$rc_tmp"
    unset PROXY_CREDENTIAL
}
trap cleanup EXIT

printf '%s' "$PROXY_CREDENTIAL" | python3 -c \
    'import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read(), safe=""), end="")' \
    >"$secret_tmp"
chmod 0600 "$secret_tmp"
mv -f -- "$secret_tmp" "$SECRET_FILE"

{
    printf '%s\n' '# Generated by pto-auth-proxy join. Do not put secrets in this file.'
    printf '%s\n' '_pto_proxy_secret_file="${XDG_CONFIG_HOME:-$HOME/.config}/pto-auth-proxy/secret-uri"'
    printf '%s\n' 'if [ -r "$_pto_proxy_secret_file" ]; then'
    printf '%s\n' '    _pto_proxy_secret_uri=$(cat -- "$_pto_proxy_secret_file")'
    printf '    _pto_proxy_url="http://%s:${_pto_proxy_secret_uri}@%s:%s"\n' \
        "$PROXY_USER" "$HTTP_URL_HOST" "$HTTP_PORT"
    printf '    _pto_proxy_socks_url="socks5h://%s:${_pto_proxy_secret_uri}@%s:%s"\n' \
        "$PROXY_USER" "$HTTP_URL_HOST" "$SOCKS_PORT"
    printf '%s\n' '    export HTTPS_PROXY="$_pto_proxy_url"'
    printf '%s\n' '    export HTTP_PROXY="$_pto_proxy_url"'
    printf '%s\n' '    export https_proxy="$_pto_proxy_url"'
    printf '%s\n' '    export http_proxy="$_pto_proxy_url"'
    printf '%s\n' '    export ALL_PROXY="$_pto_proxy_socks_url"'
    printf '%s\n' '    export all_proxy="$_pto_proxy_socks_url"'
    printf '%s\n' '    for _pto_proxy_no_proxy in localhost 127.0.0.0/8 ::1 169.254.169.254 192.168.0.0/16 10.0.0.0/8; do'
    printf '%s\n' '        case ",${NO_PROXY:-}," in'
    printf '%s\n' '            *",${_pto_proxy_no_proxy},"*) ;;'
    printf '%s\n' '            *) NO_PROXY="${NO_PROXY:+$NO_PROXY,}${_pto_proxy_no_proxy}" ;;'
    printf '%s\n' '        esac'
    printf '%s\n' '    done'
    printf '%s\n' '    export NO_PROXY'
    printf '%s\n' '    export no_proxy="$NO_PROXY"'
    printf '%s\n' '    unset _pto_proxy_secret_uri _pto_proxy_url _pto_proxy_socks_url _pto_proxy_no_proxy'
    printf '%s\n' 'fi'
    printf '%s\n' 'unset _pto_proxy_secret_file'
} >"$env_tmp"
chmod 0600 "$env_tmp"
mv -f -- "$env_tmp" "$ENV_FILE"

rc_tmp=$(mktemp "${SHELL_RC}.pto-auth-proxy.XXXXXX")
awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" \
    -v legacy_begin="$LEGACY_BEGIN_MARKER" -v legacy_end="$LEGACY_END_MARKER" '
    $0 == begin || $0 == legacy_begin { skipping = 1; next }
    ($0 == end || $0 == legacy_end) && skipping { skipping = 0; next }
    !skipping { print }
' "$SHELL_RC" >"$rc_tmp"
{
    printf '%s\n' "$BEGIN_MARKER"
    printf '%s\n' '[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/pto-auth-proxy/env.sh" ] && \'
    printf '%s\n' '    . "${XDG_CONFIG_HOME:-$HOME/.config}/pto-auth-proxy/env.sh"'
    printf '%s\n' "$END_MARKER"
} >>"$rc_tmp"
chmod --reference="$SHELL_RC" "$rc_tmp"

if ! cmp -s "$SHELL_RC" "$rc_tmp"; then
    backup="${SHELL_RC}.pto-auth-proxy.bak.$(date +%Y%m%d%H%M%S)"
    cp -p -- "$SHELL_RC" "$backup"
    chmod go-rwx "$backup"
    mv -f -- "$rc_tmp" "$SHELL_RC"
    rc_tmp=
    echo "Updated $SHELL_RC_DISPLAY (backup: $backup)"
else
    rm -f -- "$rc_tmp"
    rc_tmp=
    echo "$SHELL_RC_DISPLAY is already configured"
fi

echo "Stored proxy credentials in $SECRET_FILE (mode 0600)"
echo "New shells will use authenticated proxies $HTTP_HOST:$HTTP_PORT (HTTP) and $HTTP_HOST:$SOCKS_PORT (SOCKS5)"
